export const initialValues = {
          fullName: "",
          email: "",
          phoneNo: null,
          password: "",
          cPassword: "",
          expectedSalary: 0,
          gender: "",
          conditionAcceptance: false,
          skills: [],
          country: "",
          state: "",
          city: "",
          dob: "",
          joiningDate: "",
          dateRangeStart: "",
          dateRangeEnd: "",
          coverLetter: "",
          resume: null as File | null,
        }